[package]
name = "ownmesh-policy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true
description = "ownmesh-policy"
readme = "README.md"

[lints]
workspace = true

[dependencies]
ownmesh-domain = { path = "../ownmesh-domain" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
toml = "1.1"

[dev-dependencies]

