//! Durable, owner-bound PTY output spool primitives for the session supervisor.
//!
//! The supervisor may expose this state only through OwnMesh local IPC. The
//! underlying files use the same pinned owner/DACL/no-reparse custody helpers as
//! the daemon credential registry; this is not a same-user malware boundary.

use ownmesh_ipc::{
    atomic_write_owner_only, create_owner_only_file_new, prepare_owner_only_state_dir,
    read_owner_only_file_bounded,
};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use uuid::Uuid;

/// Maximum retained PTY output per persistent supervisor session.
pub const SUPERVISOR_SPOOL_MAX_BYTES: usize = 1024 * 1024;
const MANIFEST_FILE: &str = "host-manifest.json";
const SPOOL_FILE: &str = "owner-output.spool";
const CLAIM_FILE: &str = "host.claim";
const MAX_MANIFEST_BYTES: usize = 16 * 1024;
const SPOOL_MAGIC: &[u8; 8] = b"OMSP001\0";
const SPOOL_HEADER_BYTES: usize = 16;

/// Durable identity expected by a daemon reattach request.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HostManifest {
    pub session_id: String,
    pub device_id: String,
    pub workspace_id: String,
    pub owner_principal: String,
    /// Generated by the supervisor, never an MCP caller.
    pub host_nonce: String,
    pub controller_epoch: u64,
    pub expires_unix: i64,
}

impl HostManifest {
    pub fn new(
        session_id: impl Into<String>,
        device_id: impl Into<String>,
        workspace_id: impl Into<String>,
        owner_principal: impl Into<String>,
        controller_epoch: u64,
        expires_unix: i64,
    ) -> Result<Self, String> {
        let manifest = Self {
            session_id: session_id.into(),
            device_id: device_id.into(),
            workspace_id: workspace_id.into(),
            owner_principal: owner_principal.into(),
            host_nonce: format!("host_{}", Uuid::new_v4().simple()),
            controller_epoch,
            expires_unix,
        };
        manifest.validate()?;
        Ok(manifest)
    }

    pub fn validate(&self) -> Result<(), String> {
        for (field, value) in [
            ("session_id", self.session_id.as_str()),
            ("device_id", self.device_id.as_str()),
            ("workspace_id", self.workspace_id.as_str()),
            ("owner_principal", self.owner_principal.as_str()),
            ("host_nonce", self.host_nonce.as_str()),
        ] {
            if !valid_component(value) {
                return Err(format!("invalid supervisor {field}"));
            }
        }
        if self.controller_epoch == 0 || self.expires_unix <= 0 {
            return Err("invalid supervisor epoch or expiry".into());
        }
        Ok(())
    }
}

/// A bounded spool page. Offsets are absolute, never compacted physical bytes.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpoolPage {
    pub bytes: Vec<u8>,
    pub next_offset: Option<u64>,
    /// Absolute tail offset, not retained byte count.
    pub total_bytes: u64,
    /// Cursor was before the retained absolute base; resume at `next_offset`.
    pub truncated: bool,
}

/// A session-specific private spool rooted in a custody-attested directory.
pub struct OwnerSpool {
    dir: PathBuf,
    manifest: HostManifest,
}

impl OwnerSpool {
    pub fn create(root: &Path, manifest: HostManifest) -> Result<Self, String> {
        manifest.validate()?;
        prepare_owner_only_state_dir(root).map_err(|e| format!("prepare spool root: {e}"))?;
        let dir = root.join(&manifest.session_id);
        fs::create_dir(&dir).map_err(|e| {
            if e.kind() == std::io::ErrorKind::AlreadyExists {
                "supervisor spool already exists (duplicate host refused)".into()
            } else {
                format!("create supervisor session spool: {e}")
            }
        })?;
        // A replacement after mkdir is detected before any manifest/output is trusted.
        if let Err(error) = prepare_owner_only_state_dir(&dir) {
            let _ = fs::remove_dir(&dir);
            return Err(format!("attest supervisor session spool: {error}"));
        }
        // Exclusive marker closes the empty-directory takeover window before
        // any replaceable metadata is created.
        create_owner_only_file_new(&dir.join(CLAIM_FILE), manifest.host_nonce.as_bytes())
            .map_err(|e| format!("claim supervisor session spool: {e}"))?;
        let manifest_bytes = serde_json::to_vec(&manifest)
            .map_err(|e| format!("encode supervisor manifest: {e}"))?;
        create_owner_only_file_new(&dir.join(MANIFEST_FILE), &manifest_bytes)
            .map_err(|e| format!("write supervisor manifest: {e}"))?;
        // State (base offset + bytes) is one atomically replaced owner-only file.
        create_owner_only_file_new(&dir.join(SPOOL_FILE), &encode_spool(0, &[]))
            .map_err(|e| format!("create supervisor spool: {e}"))?;
        Ok(Self { dir, manifest })
    }

    pub fn open(root: &Path, session_id: &str) -> Result<Self, String> {
        if !valid_component(session_id) {
            return Err("invalid supervisor session id".into());
        }
        let dir = root.join(session_id);
        prepare_owner_only_state_dir(&dir)
            .map_err(|e| format!("attest supervisor spool directory: {e}"))?;
        let bytes = read_owner_only_file_bounded(&dir.join(MANIFEST_FILE), MAX_MANIFEST_BYTES)
            .map_err(|e| format!("read supervisor manifest: {e}"))?;
        let manifest: HostManifest = serde_json::from_slice(&bytes)
            .map_err(|e| format!("parse supervisor manifest: {e}"))?;
        manifest.validate()?;
        if manifest.session_id != session_id {
            return Err("supervisor manifest/session path mismatch".into());
        }
        let spool = Self { dir, manifest };
        let _ = spool.read_state()?;
        Ok(spool)
    }

    #[must_use]
    pub fn manifest(&self) -> &HostManifest {
        &self.manifest
    }

    /// Replace the durable controller binding without altering retained PTY
    /// bytes. The caller must have already proven exact possession of the old
    /// binding; this method validates the successor before atomically replacing
    /// the manifest so a crash exposes either the old or the complete new one.
    pub fn rotate_manifest(&mut self, next: HostManifest) -> Result<(), String> {
        next.validate()?;
        if next.session_id != self.manifest.session_id
            || next.device_id != self.manifest.device_id
            || next.workspace_id != self.manifest.workspace_id
        {
            return Err("supervisor binding identity cannot change".into());
        }
        if next.controller_epoch <= self.manifest.controller_epoch {
            return Err("supervisor binding epoch must advance".into());
        }
        let bytes = serde_json::to_vec(&next)
            .map_err(|e| format!("encode rotated supervisor manifest: {e}"))?;
        atomic_write_owner_only(&self.dir.join(MANIFEST_FILE), &bytes)
            .map_err(|e| format!("rotate supervisor manifest: {e}"))?;
        self.manifest = next;
        Ok(())
    }

    /// Atomically append bounded output. Dropping head bytes increments the
    /// durable absolute base offset, so cursors never rewind into different data.
    pub fn append(&self, bytes: &[u8]) -> Result<(), String> {
        if bytes.len() > SUPERVISOR_SPOOL_MAX_BYTES {
            return Err("supervisor output chunk exceeds spool budget".into());
        }
        let (base, retained) = self.read_state()?;
        let drop_count = retained
            .len()
            .saturating_add(bytes.len())
            .saturating_sub(SUPERVISOR_SPOOL_MAX_BYTES);
        let next_base = base
            .checked_add(u64::try_from(drop_count).map_err(|_| "supervisor offset overflow")?)
            .ok_or("supervisor offset overflow")?;
        let mut next = Vec::with_capacity(retained.len().saturating_sub(drop_count) + bytes.len());
        next.extend_from_slice(&retained[drop_count..]);
        next.extend_from_slice(bytes);
        atomic_write_owner_only(&self.dir.join(SPOOL_FILE), &encode_spool(next_base, &next))
            .map_err(|e| format!("write supervisor spool: {e}"))
    }

    pub fn read_page(&self, offset: u64, max_bytes: usize) -> Result<SpoolPage, String> {
        if max_bytes == 0 || max_bytes > SUPERVISOR_SPOOL_MAX_BYTES {
            return Err("invalid supervisor spool page budget".into());
        }
        let (base, retained) = self.read_state()?;
        let tail = base
            .checked_add(u64::try_from(retained.len()).map_err(|_| "supervisor offset overflow")?)
            .ok_or("supervisor offset overflow")?;
        if offset < base {
            return Ok(SpoolPage {
                bytes: vec![],
                next_offset: Some(base),
                total_bytes: tail,
                truncated: true,
            });
        }
        if offset > tail {
            return Err("supervisor spool cursor is beyond tail".into());
        }
        let start = usize::try_from(offset - base).map_err(|_| "supervisor cursor too large")?;
        let end = start.saturating_add(max_bytes).min(retained.len());
        let bytes = retained[start..end].to_vec();
        let next = offset + bytes.len() as u64;
        Ok(SpoolPage {
            bytes,
            next_offset: (next < tail).then_some(next),
            total_bytes: tail,
            truncated: false,
        })
    }

    fn read_state(&self) -> Result<(u64, Vec<u8>), String> {
        let bytes = read_owner_only_file_bounded(
            &self.dir.join(SPOOL_FILE),
            SUPERVISOR_SPOOL_MAX_BYTES + SPOOL_HEADER_BYTES,
        )
        .map_err(|e| format!("read supervisor spool: {e}"))?;
        decode_spool(&bytes)
    }
}

fn encode_spool(base_offset: u64, payload: &[u8]) -> Vec<u8> {
    let mut out = Vec::with_capacity(SPOOL_HEADER_BYTES + payload.len());
    out.extend_from_slice(SPOOL_MAGIC);
    out.extend_from_slice(&base_offset.to_le_bytes());
    out.extend_from_slice(payload);
    out
}

fn decode_spool(bytes: &[u8]) -> Result<(u64, Vec<u8>), String> {
    if bytes.len() < SPOOL_HEADER_BYTES || &bytes[..8] != SPOOL_MAGIC {
        return Err("supervisor spool header is corrupt".into());
    }
    if bytes.len() > SUPERVISOR_SPOOL_MAX_BYTES + SPOOL_HEADER_BYTES {
        return Err("supervisor spool exceeds retained byte budget".into());
    }
    let mut base = [0_u8; 8];
    base.copy_from_slice(&bytes[8..SPOOL_HEADER_BYTES]);
    Ok((
        u64::from_le_bytes(base),
        bytes[SPOOL_HEADER_BYTES..].to_vec(),
    ))
}

fn valid_component(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 256
        && !value
            .chars()
            .any(|c| c.is_control() || c == '/' || c == '\\')
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn manifest() -> HostManifest {
        HostManifest::new(
            "ses_1",
            "dev_1",
            "ws_1",
            "client:remote:t:p",
            1,
            2_000_000_000,
        )
        .unwrap()
    }

    #[test]
    fn spool_is_bounded_and_cursor_paged_without_rewind() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        spool.append(b"abcdef").unwrap();
        assert_eq!(spool.read_page(0, 3).unwrap().next_offset, Some(3));
        spool
            .append(&vec![b'x'; SUPERVISOR_SPOOL_MAX_BYTES])
            .unwrap();
        let truncated = spool.read_page(0, 1).unwrap();
        assert!(truncated.truncated);
        let base = truncated.next_offset.unwrap();
        let page = spool.read_page(base, 3).unwrap();
        assert_eq!(page.bytes, b"xxx");
        assert!(spool.read_page(page.total_bytes + 1, 1).is_err());
    }

    #[test]
    fn manifest_and_spool_corruption_fail_closed() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        fs::write(spool.dir.join(MANIFEST_FILE), b"not-json").unwrap();
        assert!(OwnerSpool::open(temp.path(), "ses_1").is_err());
        // Recreate a clean custody-attested session for spool corruption.
        fs::remove_dir_all(spool.dir).unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        fs::write(spool.dir.join(SPOOL_FILE), b"corrupt").unwrap();
        assert!(OwnerSpool::open(temp.path(), "ses_1").is_err());
    }

    #[test]
    fn oversized_spool_is_rejected_before_decode() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        fs::write(
            spool.dir.join(SPOOL_FILE),
            vec![0_u8; SUPERVISOR_SPOOL_MAX_BYTES + SPOOL_HEADER_BYTES + 1],
        )
        .unwrap();
        assert!(OwnerSpool::open(temp.path(), "ses_1").is_err());
    }

    #[test]
    fn duplicate_host_and_path_substitution_are_rejected() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        assert!(OwnerSpool::create(temp.path(), manifest()).is_err());
        let other = temp.path().join("ses_other");
        fs::rename(temp.path().join("ses_1"), &other).unwrap();
        assert!(OwnerSpool::open(temp.path(), "ses_other").is_err());
        assert_eq!(spool.manifest().session_id, "ses_1");
    }
}
