//! Durable, owner-bound PTY output spool primitives for the session supervisor.
//!
//! This module deliberately contains no network listener. A future persistent
//! supervisor exposes it only through OwnMesh local IPC, whose peer custody and
//! per-client credential checks live in `ownmesh-ipc`.

use serde::{Deserialize, Serialize};
use std::fs::{self, File, OpenOptions};
use std::io::{Read, Seek, SeekFrom};
use std::path::{Path, PathBuf};
use uuid::Uuid;

/// Maximum retained PTY output per persistent supervisor session.
pub const SUPERVISOR_SPOOL_MAX_BYTES: usize = 1024 * 1024;
const MANIFEST_FILE: &str = "host-manifest.json";
const SPOOL_FILE: &str = "owner-output.spool";
const MAX_MANIFEST_BYTES: u64 = 16 * 1024;

/// Durable identity expected by a daemon reattach request.
///
/// `host_nonce` is generated by the out-of-process supervisor, never by an MCP
/// caller. It prevents a stale daemon process from attaching to a replacement
/// host that reused a session id.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct HostManifest {
    pub session_id: String,
    pub device_id: String,
    pub workspace_id: String,
    pub owner_principal: String,
    pub host_nonce: String,
    pub controller_epoch: u64,
    pub expires_unix: i64,
}

impl HostManifest {
    /// Construct a fresh nonce-bound manifest after validating all identifiers.
    pub fn new(
        session_id: impl Into<String>,
        device_id: impl Into<String>,
        workspace_id: impl Into<String>,
        owner_principal: impl Into<String>,
        controller_epoch: u64,
        expires_unix: i64,
    ) -> Result<Self, String> {
        let manifest = Self {
            session_id: session_id.into(),
            device_id: device_id.into(),
            workspace_id: workspace_id.into(),
            owner_principal: owner_principal.into(),
            host_nonce: format!("host_{}", Uuid::new_v4().simple()),
            controller_epoch,
            expires_unix,
        };
        manifest.validate()?;
        Ok(manifest)
    }

    pub fn validate(&self) -> Result<(), String> {
        for (field, value) in [
            ("session_id", self.session_id.as_str()),
            ("device_id", self.device_id.as_str()),
            ("workspace_id", self.workspace_id.as_str()),
            ("owner_principal", self.owner_principal.as_str()),
            ("host_nonce", self.host_nonce.as_str()),
        ] {
            if value.is_empty()
                || value.len() > 256
                || value
                    .chars()
                    .any(|c| c.is_control() || c == '/' || c == '\\')
            {
                return Err(format!("invalid supervisor {field}"));
            }
        }
        if self.controller_epoch == 0 || self.expires_unix <= 0 {
            return Err("invalid supervisor epoch or expiry".into());
        }
        Ok(())
    }
}

/// Bounded owner-only spool page. `next_offset` is absent only at retained EOF.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SpoolPage {
    pub bytes: Vec<u8>,
    pub next_offset: Option<u64>,
    pub total_bytes: u64,
    pub truncated: bool,
}

/// A session-specific spool below a private supervisor root.
pub struct OwnerSpool {
    dir: PathBuf,
    manifest: HostManifest,
}

impl OwnerSpool {
    pub fn create(root: &Path, manifest: HostManifest) -> Result<Self, String> {
        manifest.validate()?;
        fs::create_dir_all(root).map_err(|e| format!("create supervisor spool root: {e}"))?;
        let dir = root.join(&manifest.session_id);
        if dir.exists() {
            return Err("supervisor spool already exists (duplicate host refused)".into());
        }
        fs::create_dir(&dir).map_err(|e| format!("create supervisor session spool: {e}"))?;
        let bytes = serde_json::to_vec(&manifest)
            .map_err(|e| format!("encode supervisor manifest: {e}"))?;
        fs::write(dir.join(MANIFEST_FILE), bytes)
            .map_err(|e| format!("write supervisor manifest: {e}"))?;
        File::create(dir.join(SPOOL_FILE)).map_err(|e| format!("create supervisor spool: {e}"))?;
        Ok(Self { dir, manifest })
    }

    pub fn open(root: &Path, session_id: &str) -> Result<Self, String> {
        if !valid_session_id(session_id) {
            return Err("invalid supervisor session id".into());
        }
        let dir = root.join(session_id);
        let manifest_path = dir.join(MANIFEST_FILE);
        if fs::metadata(&manifest_path)
            .map_err(|e| format!("stat supervisor manifest: {e}"))?
            .len()
            > MAX_MANIFEST_BYTES
        {
            return Err("supervisor manifest exceeds byte budget".into());
        }
        let bytes =
            fs::read(manifest_path).map_err(|e| format!("read supervisor manifest: {e}"))?;
        let manifest: HostManifest = serde_json::from_slice(&bytes)
            .map_err(|e| format!("parse supervisor manifest: {e}"))?;
        manifest.validate()?;
        if manifest.session_id != session_id {
            return Err("supervisor manifest/session path mismatch".into());
        }
        Ok(Self { dir, manifest })
    }

    #[must_use]
    pub fn manifest(&self) -> &HostManifest {
        &self.manifest
    }

    /// Append output without exceeding the retained ring budget. Oldest bytes
    /// are deterministically discarded and surfaced through `truncated` pages.
    pub fn append(&self, bytes: &[u8]) -> Result<(), String> {
        if bytes.len() > SUPERVISOR_SPOOL_MAX_BYTES {
            return Err("supervisor output chunk exceeds spool budget".into());
        }
        let path = self.dir.join(SPOOL_FILE);
        let current_len = fs::metadata(&path)
            .map_err(|e| format!("stat supervisor spool: {e}"))?
            .len();
        if current_len > SUPERVISOR_SPOOL_MAX_BYTES as u64 {
            return Err("supervisor spool exceeds retained byte budget".into());
        }
        let current = fs::read(&path).map_err(|e| format!("read supervisor spool: {e}"))?;
        let keep_from = current
            .len()
            .saturating_add(bytes.len())
            .saturating_sub(SUPERVISOR_SPOOL_MAX_BYTES);
        let mut next = Vec::with_capacity(current.len().saturating_sub(keep_from) + bytes.len());
        next.extend_from_slice(&current[keep_from..]);
        next.extend_from_slice(bytes);
        fs::write(path, next).map_err(|e| format!("write supervisor spool: {e}"))
    }

    pub fn read_page(&self, offset: u64, max_bytes: usize) -> Result<SpoolPage, String> {
        if max_bytes == 0 || max_bytes > SUPERVISOR_SPOOL_MAX_BYTES {
            return Err("invalid supervisor spool page budget".into());
        }
        let path = self.dir.join(SPOOL_FILE);
        let total = fs::metadata(&path)
            .map_err(|e| format!("stat supervisor spool: {e}"))?
            .len();
        if total > SUPERVISOR_SPOOL_MAX_BYTES as u64 {
            return Err("supervisor spool exceeds retained byte budget".into());
        }
        let bounded_offset = offset.min(total);
        let mut file = OpenOptions::new()
            .read(true)
            .open(path)
            .map_err(|e| format!("open supervisor spool: {e}"))?;
        file.seek(SeekFrom::Start(bounded_offset))
            .map_err(|e| format!("seek supervisor spool: {e}"))?;
        let mut bytes = vec![0; ((total - bounded_offset) as usize).min(max_bytes)];
        file.read_exact(&mut bytes)
            .map_err(|e| format!("read supervisor spool: {e}"))?;
        let next = bounded_offset + bytes.len() as u64;
        Ok(SpoolPage {
            bytes,
            next_offset: (next < total).then_some(next),
            total_bytes: total,
            // Offsets are physical retained-spool offsets. An offset below the
            // retained head is impossible with this single-file bounded ring,
            // so report truncation only through explicit size/continuation facts.
            truncated: total as usize >= SUPERVISOR_SPOOL_MAX_BYTES,
        })
    }
}

fn valid_session_id(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= 256
        && !value
            .chars()
            .any(|c| c.is_control() || c == '/' || c == '\\')
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn manifest() -> HostManifest {
        HostManifest::new(
            "ses_1",
            "dev_1",
            "ws_1",
            "client:remote:t:p",
            1,
            2_000_000_000,
        )
        .unwrap()
    }

    #[test]
    fn spool_is_bounded_and_cursor_paged() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        spool.append(b"abcdef").unwrap();
        let first = spool.read_page(0, 3).unwrap();
        assert_eq!(first.bytes, b"abc");
        assert_eq!(first.next_offset, Some(3));
        assert_eq!(spool.read_page(3, 3).unwrap().bytes, b"def");
        assert!(
            OwnerSpool::create(temp.path(), manifest()).is_err(),
            "duplicate host refused"
        );
    }

    #[test]
    fn manifest_path_substitution_is_rejected() {
        let temp = tempdir().unwrap();
        let spool = OwnerSpool::create(temp.path(), manifest()).unwrap();
        let other = temp.path().join("ses_other");
        fs::rename(temp.path().join("ses_1"), &other).unwrap();
        assert!(OwnerSpool::open(temp.path(), "ses_other").is_err());
        assert_eq!(spool.manifest().session_id, "ses_1");
    }
}
